# Generated by Django 2.1.7 on 2019-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_language',
            name='read_language',
            field=models.ManyToManyField(related_name='read_language', to='djangoapp.Language'),
        ),
    ]
