# Generated by Django 2.1.7 on 2019-04-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20190419_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
