# Generated by Django 2.1.7 on 2019-04-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_auto_20190419_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_language',
            name='read_language',
        ),
        migrations.RemoveField(
            model_name='student_language',
            name='speak_language',
        ),
        migrations.RemoveField(
            model_name='student_language',
            name='write_language',
        ),
    ]
