# Generated by Django 2.1.7 on 2019-04-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_auto_20190419_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_language',
            name='read_language',
        ),
        migrations.RemoveField(
            model_name='student_language',
            name='speak_language',
        ),
        migrations.RemoveField(
            model_name='student_language',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student_language',
            name='write_language',
        ),
        migrations.DeleteModel(
            name='Student_Language',
        ),
    ]
