# Generated by Django 2.1.7 on 2019-04-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_student_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_code', models.SlugField()),
                ('skill_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category_code', models.SlugField()),
                ('skill_category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_category_id',
            field=models.ForeignKey(on_delete='CASCADE', to='djangoapp.Skill_Categories'),
        ),
    ]
