# Generated by Django 2.1.7 on 2019-04-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_student_academics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Employment_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField()),
                ('date_of_relieving', models.DateField()),
                ('company_name', models.TextField(max_length=50)),
                ('designation', models.CharField(max_length=20)),
                ('employment_status', models.BooleanField()),
                ('student_id', models.ForeignKey(on_delete='CASCADE', to='djangoapp.Student')),
            ],
        ),
    ]
