# Generated by Django 2.1.7 on 2019-04-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0019_student_visa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name_as_on_passport', models.CharField(max_length=50)),
                ('passport_number', models.BigIntegerField()),
                ('passport_validity', models.DateField()),
                ('passport_status', models.BooleanField()),
                ('passport_issued_at', models.TextField(max_length=50)),
                ('student_id', models.ForeignKey(on_delete='CASCADE', to='djangoapp.Student')),
            ],
        ),
    ]
