# Generated by Django 2.1.7 on 2019-04-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_auto_20190420_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('', ''), ('good', 'Good'), ('average', 'Average'), ('excellent', 'Excellent'), ('poor', 'Poor')], max_length=20)),
                ('read_language', models.ManyToManyField(related_name='read_language', to='djangoapp.Language')),
                ('speak_language', models.ManyToManyField(related_name='speak_language', to='djangoapp.Language')),
                ('student_id', models.ForeignKey(on_delete='CASCADE', to='djangoapp.Student')),
                ('write_language', models.ManyToManyField(related_name='write_language', to='djangoapp.Language')),
            ],
        ),
    ]
