# Generated by Django 2.1.7 on 2019-04-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_student_skill_skill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.SlugField()),
                ('certificate_description', models.TextField(max_length=100)),
                ('institution_name', models.TextField(max_length=50)),
                ('certificate_validity', models.DateField()),
                ('certificate_duration', models.CharField(max_length=10)),
                ('student_id', models.ForeignKey(on_delete='CASCADE', to='djangoapp.Student')),
            ],
        ),
    ]
